# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f4b7c8c1c6f1a6269846f25bfe635c8eccca6f19fb16a0d911d3b49afd3a4889004788752dab90b62fd373f889285fd96b7790821a14fa9db56a4915f4f07a

test:
  secret_key_base: 00a582106427191e2b78cfab58690b28e3a65f8b3e101871aeb380ba8baf9e8fcb90af14049f89350571640e686b0aaf132d19686009732dbfdb166bcdab8be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
